// Remote MCP transport - lets an MCP client (Claude Code, Claude Desktop,
// claude.ai connectors) talk to this same tools/resources over HTTPS
// instead of spawning server.js locally over stdio. Mounted at /mcp by
// index.js.
//
// Auth: each request carries a personal access token (generated by the
// signed-in user from the web app, see routes/mcpTokens.js) as
// `Authorization: Bearer <token>`. That's resolved to a user id per
// request - there's no shared secret and no server-side config tying
// the deployment to one account, so any signed-up user can connect with
// their own token and only ever sees their own data.
//
// Stateless: each request gets its own McpServer + transport instance
// (per the SDK's documented stateless pattern), so concurrent requests
// from different users never share JSON-RPC request IDs or user
// context. There's no server-initiated push in this app, so GET (SSE
// stream) and DELETE (session close) aren't needed.
import express from 'express';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { registerTools } from './tools.js';
import { registerResources } from './resources.js';
import { httpUserContext } from './context.js';
import { resolveUserIdFromToken } from '../services/mcpTokenService.js';

async function requireMcpToken(req, res, next) {
  const header = req.get('authorization') || '';
  const [scheme, token] = header.split(' ');
  if (scheme !== 'Bearer' || !token) {
    res.status(401).json({ error: 'Missing bearer token. Generate one from the web app and pass it as `Authorization: Bearer <token>`.' });
    return;
  }

  const userId = await resolveUserIdFromToken(token);
  if (!userId) {
    res.status(401).json({ error: 'Invalid or revoked token' });
    return;
  }

  req.mcpUserId = userId;
  next();
}

export const mcpRouter = express.Router();

mcpRouter.use(requireMcpToken);

mcpRouter.post('/', async (req, res) => {
  await httpUserContext.run(req.mcpUserId, async () => {
    const server = new McpServer({ name: 'task-manager-mcp', version: '1.0.0' });
    registerTools(server);
    registerResources(server);
    const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });

    res.on('close', () => {
      transport.close();
      server.close();
    });

    await server.connect(transport);
    await transport.handleRequest(req, res, req.body);
  });
});

mcpRouter.get('/', (req, res) => {
  res.status(405).json({ error: 'Method not allowed - this server does not use server-initiated notifications' });
});

mcpRouter.delete('/', (req, res) => {
  res.status(405).json({ error: 'Method not allowed - this server is stateless, there is no session to close' });
});
